# EVALUACION EXHAUSTIVA

In [187]:


import numpy as np
import wolframalpha
client = wolframalpha.Client("K56TY6-XQUK252299")
from ipywidgets import Layout, Button, Box, VBox

# Items flex proportionally to the weight and the left over space around the text
items_0 = [widgets.FloatText(value=i+1) for i in range(0,4)]
items_1 = [widgets.FloatText(value=i+1) for i in range(4,8)]
items_2 = [widgets.FloatText(value=i+1) for i in range(8,12)]
items_3 = [widgets.FloatText(value=i+1) for i in range(12,16)]
box_layout = Layout(display='flex',
                    flex_flow='row',
                    align_items='stretch',
                    width='100%')
box_0 = Box(children=items_0, layout=box_layout)
box_1 = Box(children=items_1, layout=box_layout)
box_2 = Box(children=items_2, layout=box_layout)
box_3 = Box(children=items_3, layout=box_layout)
VBox([box_0,box_1,box_2,box_3])


In [171]:
res = client.query('temperature in Washington, DC on October 3, 2012')
res

{'@success': 'true',
 '@error': 'false',
 '@numpods': '5',
 '@datatypes': 'Weather',
 '@timedout': '',
 '@timedoutpods': '',
 '@timing': '5.296',
 '@parsetiming': '2.112',
 '@parsetimedout': 'false',
 '@recalculate': '',
 '@id': 'MSPa1049612d6c9h65a14da6b000016509ci667e2g1d5',
 '@host': 'https://www4b.wolframalpha.com',
 '@server': '33',
 '@related': 'https://www4b.wolframalpha.com/api/v2/relatedQueries.jsp?id=MSPa1049712d6c9h65a14da6b000012ae64ii84c0he1e4003125516353033000',
 '@version': '2.6',
 'pod': [{'@title': 'Input interpretation',
   '@scanner': 'Identity',
   '@id': 'Input',
   '@position': '100',
   '@error': 'false',
   '@numsubpods': '1',
   'subpod': {'@title': '',
    'img': {'@src': 'https://www4b.wolframalpha.com/Calculate/MSP/MSP1049812d6c9h65a14da6b00006aiab768358e9549?MSPStoreType=image/gif&s=33',
     '@alt': 'temperature | Washington, United States Wednesday, October 3, 2012',
     '@title': 'temperature | Washington, United States Wednesday, October 3, 2012',
    

In [169]:
print('Politica a evaluar separada por comas')
poli=widgets.Text(
    placeholder='1,2,3,1')
poli

Politica a evaluar separada por comas


Text(value='', placeholder='1,2,3,1')

In [178]:
arr=[[.48,.30,.22,0],[.59,.27,.14,0],[.43,.26,.31,0],[0,0,0,0]]
#arr=[[items_0[i].value for i in range(0,4)]
#     ,[items_1[i].value for i in range(0,4)]
#     ,[items_2[i].value for i in range(0,4)]
#     ,[items_3[i].value for i in range(0,4)]]
original=np.array(arr)
original
#IPython.notebook.execute_all_cells()

array([[0.48, 0.3 , 0.22, 0.  ],
       [0.59, 0.27, 0.14, 0.  ],
       [0.43, 0.26, 0.31, 0.  ],
       [0.  , 0.  , 0.  , 0.  ]])

In [179]:
np.sum(original,axis=1)

array([1., 1., 1., 0.])

In [180]:

pol=[1,1,1,3]
for i in range(0,4):
    if pol[i]==1:
        continue
    elif pol[i]==2:
        for j in range(0,4):
            if j==1:
                original[i][j]=1
            else:
                original[i][j]=0
    elif pol[i]==3:
        for j in range(0,4):
            if j==0:
                original[i][j]=1
            else:
                original[i][j]=0
            
original

array([[0.48, 0.3 , 0.22, 0.  ],
       [0.59, 0.27, 0.14, 0.  ],
       [0.43, 0.26, 0.31, 0.  ],
       [1.  , 0.  , 0.  , 0.  ]])

In [181]:
trans=np.transpose(original)
trans

array([[0.48, 0.59, 0.43, 1.  ],
       [0.3 , 0.27, 0.26, 0.  ],
       [0.22, 0.14, 0.31, 0.  ],
       [0.  , 0.  , 0.  , 0.  ]])

In [182]:
for i in range(0,4):
    trans[i][i]=trans[i][i]-1
trans

array([[-0.52,  0.59,  0.43,  1.  ],
       [ 0.3 , -0.73,  0.26,  0.  ],
       [ 0.22,  0.14, -0.69,  0.  ],
       [ 0.  ,  0.  ,  0.  , -1.  ]])

In [183]:
for i in range(0,4):
    print("{} {} {} {} 0".format(trans[i][0],trans[i][1],trans[i][2],trans[i][3]))
print("1 1 1 1 1")

-0.52 0.59 0.43 1.0 0
0.3 -0.73 0.26 0.0 0
0.22 0.14 -0.69 0.0 0
0.0 0.0 0.0 -1.0 0
1 1 1 1 1


In [155]:
costo=np.array([[7700,14500,0],[11700,18500,0],[16700,23500,26400],[0,0,26400]])
pi=[2950/6563,2600/6563,1013/6563,0]
costo=np.transpose(costo)
costo

array([[ 7700, 11700, 16700,     0],
       [14500, 18500, 23500,     0],
       [    0,     0, 26400, 26400]])

In [156]:
x_1=4673/9341
x_2=2642/9341
x_3=2026/9341
x_4=0
pi=np.array([x_1,x_2,x_3,x_4])
pi=np.around(pi, decimals=2)

pi

array([0.5 , 0.28, 0.22, 0.  ])

In [157]:
total=np.zeros((4,))
cont=0
for i in pol:
    total[cont]=costo[i-1][cont]
    cont+=1
total

array([ 7700., 11700., 16700., 26400.])

In [158]:
res=np.sum(np.multiply(total,pi),axis=0)
res

10800.0

In [159]:
print("Politica a evaluar", pol)
print("\n")
for i in range(0,4):
    print("{}a+ {}b+ {}c+ {}d= 0".format(trans[i][0],trans[i][1],trans[i][2],trans[i][3]))
print("a+b+c+d=1")

print("\n Vector PI ",pi)

print("\n {}*{} + {}*{} + {}*{} + {}*{}={}".format(pi[0],total[0],pi[1],total[1],pi[2],total[2],pi[3],total[3],res))

print("\n EL resultado es ",res)

Politica a evaluar [1, 1, 1, 3]


0.0a+ 5.0b+ 9.0c+ 1.0d= 0
2.0a+ 5.0b+ 10.0c+ 0.0d= 0
3.0a+ 7.0b+ 10.0c+ 0.0d= 0
4.0a+ 8.0b+ 12.0c+ -1.0d= 0
a+b+c+d=1

 Vector PI  [0.5  0.28 0.22 0.  ]

 0.5*7700.0 + 0.28*11700.0 + 0.22*16700.0 + 0.0*26400.0=10800.0

 EL resultado es  10800.0


In [173]:
def gauss(A):
    n = len(A)

    for i in range(0, n):
        # Search for maximum in this column
        maxEl = abs(A[i][i])
        maxRow = i
        for k in range(i+1, n):
            if abs(A[k][i]) > maxEl:
                maxEl = abs(A[k][i])
                maxRow = k

        # Swap maximum row with current row (column by column)
        for k in range(i, n+1):
            tmp = A[maxRow][k]
            A[maxRow][k] = A[i][k]
            A[i][k] = tmp

        # Make all rows below this one 0 in current column
        for k in range(i+1, n):
            c = -A[k][i]/A[i][i]
            for j in range(i, n+1):
                if i == j:
                    A[k][j] = 0
                else:
                    A[k][j] += c * A[i][j]

    # Solve equation Ax=b for an upper triangular matrix A
    x = [0 for i in range(n)]
    for i in range(n-1, -1, -1):
        x[i] = A[i][n]/A[i][i]
        for k in range(i-1, -1, -1):
            A[k][n] -= A[k][i] * x[i]
    return x

In [186]:
gauss([[-0.52,  0.59,  0.43,  1.  ,0],
       [ 0.3 , -0.73,  0.26,  0.  ,0],
       [ 0.22,  0.14, -0.69,  0.  ,0],
       [ 0.  ,  0.  ,  0.  , -1.  ,0],
       [1    ,  1   ,   1  ,   1  ,1]])

IndexError: list index out of range